# Generated by Django 5.2 on 2025-04-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskmanager", "0005_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(),
        ),
    ]
