# Generated by Django 5.2 on 2025-04-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskmanager", "0006_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["deadline"]},
        ),
    ]
